---
title: "Hafro goes R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Preamble

The lecture series will tackle some recent development in R. The intended structure of the course is to have a weekly seminar/practical lab which introduces a particular topic followed by a small assignment as well as suggested further readings.

The series is intended for those that have not very much experience in using R as their daily working environment. The instructors will be Bjarki Þór Elvarsson and Einar Hjörleifsson.

The seminars will be in English, this being because the R environment is in that language as well as to accommodate potential participants whose native language may be other then Icelandic.

### Friday, 22. January 2016 - 13:30 - 15:30

* RStudio and project management
* Basis of reproducible analysis and document writing

### Friday, 19. January 2016 - 13:30 - 15:30

* Getting data into R - introduction
* Introduction to the grammar of graphics - the ggplot2 library

### Friday, 5. February 2016 - 13:30 - 15:30

* Getting data into R - beyond introduction
* Introduction to the grammar of data - the dplyr library

### Friday, 12. January 2016 - 13:30 - 15:30

* Data exploration based on grammar of data and graphics

### Friday, 29. February 2016 - 13:30 - 15:30

* More data exploration based on grammar of data and graphics

